### ISSUE TITLE
Jinja template usage

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/BluePyMM#227]
@anilbey, would you mind having a look at the usage of the jinja template parameter in bluepymm.
@jjt20, pointed out that it seems the 'template' parameter, as in:
https://github.com/BlueBrain/BluePyMM/blob/1f87b5125d178a0a6d65672e612fefbca38ae65d/bluepymm/tests/examples/simple1/simple1_conf_hoc.json
doesn't seem to work (he provides a jinja template, but it doesn't seem to be used).
When looking at the code itself, it also seems the location of the jinja template is hard coded

**Comment by anilbey** [comment]
Sure @wvangeit let me check.
